version: '3.3'

services:
  r-odaf:
    restart: "unless-stopped"
    container_name: R-ODAF
    volumes:
      - project_data:/home/R-ODAF/R-ODAF_Health_Canada/
    image: mattjmeier/r-odaf-hc:latest
    entrypoint: /bin/bash -l
    tty: true

  rstudio:
    image: rocker/tidyverse
    restart: "unless-stopped"
    container_name: rstudio-server
    ports:
      - 8789:8788
    volumes:
      - project_data:/home/rstudio/project
    environment:
      - R_LIBS=${R_LIBS-'/usr/local/lib/R/site-library:/usr/local/lib/R/library'}
      - PASSWORD=changeme

volumes:
  project_data:
    external: true
    name: project_data
