version: '3.3'
services:
  r-odaf:
    container_name: R-ODAF
    volumes:
      - './data:/home/R-ODAF/R-ODAF_Health_Canada/data/raw'
      - './output:/home/R-ODAF/R-ODAF_Health_Canada/analysis/'
    image: mattjmeier/r-odaf-hc
    networks:
      - default

networks:
  default:

volumes:
  raw-data:
  output:
