name: R-ODAF_pre-processing
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - rsem=1.3.3
  - anaconda-clean=1.1.1
  - fastp=0.23.2
  - star=2.7.10b
  - multiqc=1.12
  - snakemake=7.19.1